services:
  db:
    image: mysql:8
    container_name: mysql_transporte
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "transporte"
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  web:
    build: ./web
    container_name: web_transporte
    environment:
      DB_HOST: "db"
      DB_USER: "root"
      DB_PASS: "1234"
      DB_NAME: "transporte"
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped