CREATE DATABASE IF NOT EXISTS transporte;
USE transporte;

CREATE TABLE clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  cedula VARCHAR(20) NOT NULL UNIQUE,
  telefono VARCHAR(20) NOT NULL,
  fecha_registro DATE NOT NULL,
  es_frecuente BOOLEAN NOT NULL DEFAULT FALSE,
  email VARCHAR(120) NULL
);

CREATE TABLE reservas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cliente_id INT NOT NULL,
  fecha_servicio DATETIME NOT NULL,
  origen VARCHAR(120) NOT NULL,
  destino VARCHAR(120) NOT NULL,
  valor_cop INT NOT NULL,
  confirmada BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_reservas_clientes
    FOREIGN KEY (cliente_id) REFERENCES clientes(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);